name: Continuous Integration
on:
 workflow_dispatch:
jobs:
  checkov:
    runs-on: [ubuntu-latest]
    permissions:
      contents: read
      pull-requests: write
    container: node:gallium-alpine
    steps:
      - name: Setup requirements
        run: |
          apk update && apk add --no-cache jq py3-pip && ln -sf python3 /usr/bin/python
      - name: check directory
        run: ls /usr/bin
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_wrapper: false
      - name: Setup checkov
        run: |
          pip3 install checkov
      - name: Checkout sourcecode
        uses: actions/checkout@v3.3.0
      - name: Checkov
        run: |
          checkov -d . --quiet --framework terraform --create-baseline
          checkov -d . --quiet --framework terraform --output github_failed_only --output-file-path results --baseline .checkov.baseline -s
      - name: Update Pull Request
        if: always()
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const fs = require('fs')
            const checkovResults = fs.readFileSync('./results/results_github_failed_only.md')
            const commentTemplate = `## Checkov findings
            <details>
            <summary>Show findings</summary>
            \`\`\`markdown
            {{ checkovResults }}
            \`\`\`
            </details>
            `;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentTemplate
            })
