name: Continuous Integration
on:
 workflow_dispatch:
jobs:
  checkov:
    runs-on: [ubuntu-latest]
    permissions:
      contents: read
      pull-requests: write
    container: node:gallium-alpine
    steps:
      - name: Setup requirements
        run: |
          apk update && apk add --no-cache jq py3-pip
          whereis pip
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_wrapper: false
      - name: Setup checkov
        run: |
          pip3 install checkov
