name: Continuous Integration
on: [pull_request]
jobs:
  checkov:
    runs-on: [ubuntu-latest]
    permissions:
      contents: read
      pull-requests: write
    container: node:gallium-alpine
    steps:
      - name: Checkout sourcecode
        uses: actions/checkout@v3.3.0
      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          # This will add both a CLI output to the console and create a results.sarif file
          output_format: github_failed_only         
          baseline: .checkov.baseline
      - name: check directory
        if: always()
        run: ls 
      - name: Update Pull Request
        if: always()
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const fs = require('fs')
            const checkovResults = fs.readFileSync('./results/results_github_failed_only.md')
            const commentTemplate = `## Checkov findings
            <details>
            <summary>Show findings</summary>
            \`\`\`markdown
            ${checkovResults} 
            \`\`\`
            </details>
            `;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentTemplate
            })
