name: Continuous Integration
on:
  pull_request:
    branches: [main]
jobs:
  terraform-checks:
    name: Terraform Checks
    runs-on: [ubuntu-latest] 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.1.0     
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: terraform install
        run: |
          sudo yum install -y yum-utils
          sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
          sudo yum -y install terraform
          ls
          pwd
          ls /etc/yum.repos.d/hashicorp.repo
      - name: Terraform Format
        run: | 
         terraform fmt
      - name: Terraform Init
        run: terraform init > result_init.txt
      - name: PR comment with file
        if: success() || failure()
        uses: thollander/actions-comment-pull-request@v2
        with:
           filePath: ./result_init.txt
      - name: dir
        run: ls
      - name: Terraform Validate
        if: success() || failure()
        run: |
            terraform validate -no-color > result_validate.txt
           
      - name: PR comment with file
        if: success() || failure()
        uses: thollander/actions-comment-pull-request@v2
        with:
           filePath: ./result_validate.txt
