name: Continuous Integration
on:
  pull_request:
    branches: [main]
jobs:
  terraform-checks:
    name: Terraform Checks
    runs-on: [ubuntu-latest] 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.1.0     
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Format
        run: | 
         terraform fmt
      - name: Terraform Init
        run: terraform init
      - name: dir
        run: ls
      - name: Terraform Validate
        if: success() || failure()
        run: |
            terraform validate -no-color > result_validate.txt
           
      - name: PR comment with file
        if: success() || failure()
        uses: thollander/actions-comment-pull-request@v2
        with:
           filePath: ./result_validate.txt
